export enum CharacterActionTypes {
    GET_CHARACTERS = 'GET_CHARACTERS',
    ADD_TO_FAVORITES = 'ADD_TO_FAVORITES',
    CLEAR_FAVORITES = 'CLEAR_FAVORITES',
    FILTER_BY_STATUS = 'FILTER_BY_STATUS'
} 
